modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "CC0-1.0 License"

[[mods]]
modId = "realmoving"
version = "${version}"
displayName = "RealMoving"
authors = "Sistr"
description = "新しい動作を追加します。"
#logoFile = ""

[[dependencies.realmoving]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realmoving]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realmoving]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"